baseURL : https://fajars.space/
languageCode : id
title : Fajar A Nugroho

params:
    description: Menulis dengan ☕️

staticDir: static

disqusShortname: fajars-space

permalinks:
  blog : /:slug/
  rekomendasi : /:slug/
  tech : /:slug/

taxonomies:
  category: categories
  tag: tags

outputs:
    home : ["HTML", "RSS", "JSON"]
